import './globals.css'
import type {Metadata} from 'next'
import StyledComponentsRegistry from "@/lib/antd-registry";
import Providers from "@/providers/query-client-provider";
import Header from "@/components/layouts/header";
import MainContainer from "@/components/layouts/main-container";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <Providers>
            <StyledComponentsRegistry>
                <Header/>
                <MainContainer>
                    {children}
                </MainContainer>
            </StyledComponentsRegistry>
        </Providers>
        </body>
        </html>
    )
}
