import './globals.css'
import type {Metadata} from 'next'
import Providers from "@/providers/query-client-provider";
import Header from "@/components/layouts/header";
import MainContainer from "@/components/layouts/main-container";
import {Toaster} from "@/components/ui/toaster";
import {Toaster as HotToaster} from 'react-hot-toast';


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body dir="rtl">
        <Providers>
            <Header/>
            <MainContainer>
                {children}
            </MainContainer>
            <Toaster/>
            <HotToaster/>
        </Providers>
        </body>
        </html>
    )
}
